name: "Tests"
on: [push, pull_request]
jobs:
  build:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup BATS
        uses: mig4/setup-bats@v1
      - name: Setup Bats libs
        uses: brokenpip3/setup-bats-libs@0.1.0
      - name: Test
        run: bats -r .
